PidFile=/run/zabbix/zabbix_agent2.pid
LogFile=/var/log/zabbix/zabbix_agent2.log
LogFileSize=0
Server=<MASKED_IP_3>,<MASKED_IP_4>
ServerActive=<MASKED_IP_3>,<MASKED_IP_4>
Hostname=<MASKED_HOSTNAME_AGENT>
PluginSocket=/run/zabbix/agent.plugin.sock
ControlSocket=/run/zabbix/agent.sock
Include=/etc/zabbix/zabbix_agent2.d/plugins.d/*.conf
Include=/etc/zabbix/zabbix_agent2.d/*.conf