LogFile=/var/log/zabbix/zabbix_server.log
LogFileSize=0
PidFile=/run/zabbix/zabbix_server.pid
SocketDir=/run/zabbix
DBHost=127.0.0.1
DBName=zabbix
DBUser=zabbix
DBPassword=
DBPort=5432
AllowUnsupportedDBVersions=1
SNMPTrapperFile=/var/log/snmptrap/snmptrap.log
Timeout=4
FpingLocation=/usr/bin/fping
Fping6Location=/usr/bin/fping6
LogSlowQueries=3000
StatsAllowedIP=127.0.0.2
EnableGlobalScripts=0
HANodeName=zabbix-server1
NodeAddress=192.168.20.5:10051
Include=/etc/zabbix/zabbix_server.d/*.conf